name: React Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build React app
        run: |
          npm install -g yarn
          npm i
          yarn build
          cd server
          npm install
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude server/.env
          remote_path: /var/node-apps/react-cms
          remote_user: ${{ secrets.USER }}
          remote_host: ${{ secrets.HOST }}
          remote_key: ${{ secrets.KEY }}
